kannel:
  image: nzuwera/kannel
  ports:
    - "13013:13013" # smsbox
    - "13000:13000" # kannel admin
  volumes:
    - "./kannel.conf:/etc/kannel/kannel.conf"
    - "./opensmppbox.conf:/etc/kannel/opensmppbox.conf"
